version: '3.8'
services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_crud
    ports:
      - "5432:5432"
    networks:
      - student-net

  backend:
    build: ./students_crud_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/students_crud
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - postgres-db
    networks:
      - student-net

  frontend:
    build: ./students_crud_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8080/api/students
    networks:
      - student-net

networks:
  student-net:
    driver: bridge
