version: '3.8'
services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_crud
    ports:
      - "5436:5432"
    networks:
      - student-net

  backend:
    build: ./students_crud_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres-db
    networks:
      - student-net

  frontend:
    build: ./students_crud_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8081/api/students
    networks:
      - student-net

networks:
  student-net:
    driver: bridge